site_name: Bits Please Technologies N.V. - Dev Docs
nav:
  - Home: index.md
  - Project Starters:
      - NextJS Starter: project-setup/next-starter.md
theme:
  name: material
  logo: images/logo.png
  features:
    - content.code.annotate

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
